version: '3'

services:

    mariadb:
        build: ./requirements/mariadb
        restart: always
        networks:
         - inception_net
        volumes:
         - db_vol:/var/lib/mysql/
        env_file: .env

    nginx:
        build: ./requirements/nginx/
        depends_on:
         - wordpress
        ports:
         - "443:443"
        restart: always
        networks:
         - inception_net
        volumes:
         - wp_vol:/var/www/

    wordpress:
        build: ./requirements/wordpress/
        depends_on:
         - mariadb
        restart: always
        networks:
         - inception_net
        volumes:
         - wp_vol:/var/www/
        env_file: .env

networks:
     inception_net:

volumes:
     wp_vol:
         driver: local
         driver_opts:
             type: 'none'
             o: 'bind'
             device: '~/data/wp'
     db_vol:
         driver: local
         driver_opts:
             type: 'none'
             o: 'bind'
             device: '~/data/db'
